/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockDependency.h"

static const char* CMockString_Dependency_Read = "Dependency_Read";
static const char* CMockString_channel = "channel";

typedef struct _CMOCK_Dependency_Read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_channel;

} CMOCK_Dependency_Read_CALL_INSTANCE;

static struct MockDependencyInstance
{
  CMOCK_MEM_INDEX_TYPE Dependency_Read_CallInstance;
} Mock;


void MockDependency_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Dependency_Read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Dependency_Read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void MockDependency_Init(void)
{
  MockDependency_Destroy();
}

void MockDependency_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int Dependency_Read(int channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Dependency_Read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Dependency_Read);
  cmock_call_instance = (CMOCK_Dependency_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Dependency_Read_CallInstance);
  Mock.Dependency_Read_CallInstance = CMock_Guts_MemNext(Mock.Dependency_Read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Dependency_Read,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Dependency_Read(CMOCK_Dependency_Read_CALL_INSTANCE* cmock_call_instance, int channel);
void CMockExpectParameters_Dependency_Read(CMOCK_Dependency_Read_CALL_INSTANCE* cmock_call_instance, int channel)
{
  cmock_call_instance->Expected_channel = channel;
}

void Dependency_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int channel, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dependency_Read_CALL_INSTANCE));
  CMOCK_Dependency_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dependency_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dependency_Read_CallInstance = CMock_Guts_MemChain(Mock.Dependency_Read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Dependency_Read(cmock_call_instance, channel);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

