/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDEPENDENCY_H
#define _MOCKDEPENDENCY_H

#include "unity.h"
#include "Dependency.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockDependency_Init(void);
void MockDependency_Destroy(void);
void MockDependency_Verify(void);




#define Dependency_Read_Expect(channel) TEST_FAIL_MESSAGE("Dependency_Read requires _ExpectAndReturn");
#define Dependency_Read_ExpectAndReturn(channel, cmock_retval) Dependency_Read_CMockExpectAndReturn(__LINE__, channel, cmock_retval)
void Dependency_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int channel, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
